//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int employeeID { get; set; }
        public string fullName { get; set; }
        public string EMPCode { get; set; }
        public string mobileNo { get; set; }
        public string postion { get; set; }
    }
}
